version: '3.9'

services:

  mongo_db:
    container_name: db_container

    image: mongo:latest

    restart: always

    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db

  api:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app
       - /usr/src/app/node_modules
    environment:
      DATABASE: mongodb://mongo_db:27017/DreamTravels
      PORT: 3000
      JWT_SEC: thisisjwtsecretkey
      SALT: 10
    depends_on: 
      - mongo_db
volumes:
  mongo_db:     